version: '3.8'
services:
  weather_test:
    image: 'kuban-weather-test:2025.1.5'
    volumes:
      - ./docker_volums/app.yml:/app/application.yml
    ports:
      - 9999:8080
    networks:
      - backend

networks:
  backend:
    driver: bridge